### ISSUE TITLE
if possible use .fxml in idea plugin ? 

### ISSUE THREAD

**Issue by icoco** [yole/javafx-demo-plugin#1]
I face a problem , while use JavaFX while building a  IDEA plugin,  seem hard to load .fxml , 
some error throws as bellows:

`
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.ClassNotFoundException: com.demo.app.MainController
	at com.intellij.util.lang.UrlClassLoader.findClass(UrlClassLoader.java:215)
Caused by: java.lang.ClassNotFoundException:com.demo.app.MainController

	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at javafx.fxml.FXMLLoader$ValueElement.processAttribute(FXMLLoader.java:931)
	... 42 more
`

the MainController.java is exist,  compile is ok but failed while run 'runIde' ...

yes, it the demo action 'JavafxDemo' works as expected, but face the problem if apply .fxml speed the gui layout design ... 

appreciate with your time

**Comment by icoco** [comment]
solve it, should be like code bellow:
`
     loader.setLocation(this.getClass().getResource(fxmlDocPath));
            // Make sure to load "Test.fxml" with the same classloader that
            // was used to load TestCanvas class.
        loader.setClassLoader(this.getClass().getClassLoader());
`
setClassLoader...
